version: 2.1

aliases:
  - &install-dependencies
    run:
      name: Install dependencies
      command: npm install
  - &create-production-bundle
    run:
      name: Generate production bundle
      command: npm run-script build

defaults: &defaults
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *install-dependencies
      - <<: *create-production-bundle

workflows:
  version: 2

  build:
    jobs:
      - build